ALTER TABLE orders ADD COLUMN IF NOT EXISTS quote_accepted_by UUID REFERENCES profiles(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS quote_accepted_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS po_signed_by UUID REFERENCES profiles(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS po_signed_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS po_reference TEXT;
